name: C/C++ CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Install misc.
      run: sudo apt install -y libboost-all-dev libgmp-dev clang-9
    - run: g++ -std=gnu++14 -O2 -Wall -o a.out arukuka.cpp -lgmp
    - run: clang++-9 -std=c++14 -O2 -Wall -o a.out arukuka.cpp -lgmp
